### ISSUE TITLE
Estou recebendo vários erros ao compilar o projeto.

### ISSUE THREAD

**Issue by jeancsanchez** [mikemajesty/Minha-Dll#1]
**File: InjectionMethod.cs**

> Error 1   ; expecte
> Error 2   Invalid token '(' in class, struct, or interface member declaration
> Error 3   Invalid token '=>' in class, struct, or interface member declaration    Minha-Dll\Mike.Utilities.Desktop\InjectionMethod.cs 163 91  Mike.Utilities.Desktop
> Error 4   Invalid token '=' in class, struct, or interface member declaration Minha-Dll\Mike.Utilities.Desktop\InjectionMethod.cs 163 101 Mike.Utilities.Desktop
> Error 5   Invalid token '.' in class, struct, or interface member declaration Mike.Utilities.Desktop\InjectionMethod.cs   163 109 Mike.Utilities.Desktop
> Error 6   Invalid token ')' in class, struct, or interface member declaration Mike.Utilities.Desktop\InjectionMethod.cs   163 115 Mike.Utilities.Desktop
> (..) 

**File: GerenciarControles.cs**

```
Error   7   ; expected Minha-Dll\Mike.Utilities.Desktop\GerenciarControles.cs   17  95  Mike.Utilities.Desktop
Error   8   Invalid token '=' in class, struct, or interface member declaration Minha-Dll\Mike.Utilities.Desktop\GerenciarControles.cs  17  110 Mike.Utilities.Desktop
Error   9   Invalid token ';' in class, struct, or interface member declaration  Minha-Dll\Mike.Utilities.Desktop\GerenciarControles.cs 17  129 Mike.Utilities.Desktop
Error   10  ; expected Minha-Dll\Mike.Utilities.Desktop\GerenciarControles.cs   23  99  Mike.Utilities.Desktop
Error   11  Invalid token '=>' in class, struct, or interface member declaration Mike.Utilities.Desktop\GerenciarControles.cs   24  13  Mike.Utilities.Desktop
(..)
```

**Comment by mikemajesty** [comment]
vc esta usnado qual vs?

2016-03-11 23:47 GMT-03:00 Jean Carlos notifications@github.com:

**Comment by jeancsanchez** [comment]
2013 Ultimate

**Comment by mikemajesty** [comment]
Eu usei o c# 6 nele, vc tem q usar o vc 2015
